'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AI_Dictionary.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property AI() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("AI", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property AI_Dictionary() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("AI_Dictionary", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property AIDabout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AIDabout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AIWelcome() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AIWelcome", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AIWelcome1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AIWelcome1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AIWelcome2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AIWelcome2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AIWelcome5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AIWelcome5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b_EE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_EE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b_EK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_EK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b_KE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_KE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b_kh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_kh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b_KK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_KK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b_KK1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_KK1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b_Speech() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_Speech", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bStop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bStop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cflag120() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cflag120", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property file() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("file", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property file2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("file2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fileWav() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fileWav", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imgRecorder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgRecorder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iSpeech1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iSpeech1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iSpeech2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iSpeech2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property recognition() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("recognition", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property save_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property saveWav() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveWav", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Searching() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Searching", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property setting() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("setting", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property sms() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sms", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sms1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sms1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smsI() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("smsI", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Speak1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Speak1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property speak2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("speak2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Speaking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Speaking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SpeakText() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpeakText", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property speech() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("speech", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property start1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("start1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property start2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("start2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stop1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stop1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stop2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stop2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
